# Generated by Django 4.0 on 2022-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoutingOptionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
